/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as NameRouteImport } from './routes/$name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as ComparePokemonRouteImport } from './routes/compare.$pokemon'
import { Route as ComparePokemonVsOpponentRouteImport } from './routes/compare.$pokemon.vs.$opponent'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRoute = NameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRoute,
} as any)
const ComparePokemonRoute = ComparePokemonRouteImport.update({
  id: '/$pokemon',
  path: '/$pokemon',
  getParentRoute: () => CompareRoute,
} as any)
const ComparePokemonVsOpponentRoute =
  ComparePokemonVsOpponentRouteImport.update({
    id: '/vs/$opponent',
    path: '/vs/$opponent',
    getParentRoute: () => ComparePokemonRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/compare': typeof CompareRouteWithChildren
  '/team': typeof TeamRoute
  '/compare/$pokemon': typeof ComparePokemonRouteWithChildren
  '/compare/': typeof CompareIndexRoute
  '/compare/$pokemon/vs/$opponent': typeof ComparePokemonVsOpponentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/team': typeof TeamRoute
  '/compare/$pokemon': typeof ComparePokemonRouteWithChildren
  '/compare': typeof CompareIndexRoute
  '/compare/$pokemon/vs/$opponent': typeof ComparePokemonVsOpponentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$name': typeof NameRoute
  '/compare': typeof CompareRouteWithChildren
  '/team': typeof TeamRoute
  '/compare/$pokemon': typeof ComparePokemonRouteWithChildren
  '/compare/': typeof CompareIndexRoute
  '/compare/$pokemon/vs/$opponent': typeof ComparePokemonVsOpponentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$name'
    | '/compare'
    | '/team'
    | '/compare/$pokemon'
    | '/compare/'
    | '/compare/$pokemon/vs/$opponent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$name'
    | '/team'
    | '/compare/$pokemon'
    | '/compare'
    | '/compare/$pokemon/vs/$opponent'
  id:
    | '__root__'
    | '/'
    | '/$name'
    | '/compare'
    | '/team'
    | '/compare/$pokemon'
    | '/compare/'
    | '/compare/$pokemon/vs/$opponent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NameRoute: typeof NameRoute
  CompareRoute: typeof CompareRouteWithChildren
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$name': {
      id: '/$name'
      path: '/$name'
      fullPath: '/$name'
      preLoaderRoute: typeof NameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/$pokemon': {
      id: '/compare/$pokemon'
      path: '/$pokemon'
      fullPath: '/compare/$pokemon'
      preLoaderRoute: typeof ComparePokemonRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/$pokemon/vs/$opponent': {
      id: '/compare/$pokemon/vs/$opponent'
      path: '/vs/$opponent'
      fullPath: '/compare/$pokemon/vs/$opponent'
      preLoaderRoute: typeof ComparePokemonVsOpponentRouteImport
      parentRoute: typeof ComparePokemonRoute
    }
  }
}

interface ComparePokemonRouteChildren {
  ComparePokemonVsOpponentRoute: typeof ComparePokemonVsOpponentRoute
}

const ComparePokemonRouteChildren: ComparePokemonRouteChildren = {
  ComparePokemonVsOpponentRoute: ComparePokemonVsOpponentRoute,
}

const ComparePokemonRouteWithChildren = ComparePokemonRoute._addFileChildren(
  ComparePokemonRouteChildren,
)

interface CompareRouteChildren {
  ComparePokemonRoute: typeof ComparePokemonRouteWithChildren
  CompareIndexRoute: typeof CompareIndexRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  ComparePokemonRoute: ComparePokemonRouteWithChildren,
  CompareIndexRoute: CompareIndexRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NameRoute: NameRoute,
  CompareRoute: CompareRouteWithChildren,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
